import { FC, useContext, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import styled from 'styled-components';

import { AppContext } from 'context';
import { BreadCrumbParent, BreadCrumbsStyled } from 'components/common/breadcrumbs';


const Styled = styled.div`
  iframe {
    border: none;
    height: 30rem;
    width: 50rem;
  }

  p {
    width: 80%
  }

`;

export const MHD3: FC = () => {

  const router = useRouter();

  const { setTabOption } = useContext(AppContext);

  // ON MOUNT: UI config
  useEffect(() => {
    setTabOption(router.asPath.split('/')[1]);
  }, []);

  const breadCrumbsParents: BreadCrumbParent[] = [
    { name: 'Visualizations', url: '/visualizations' }
  ];

  return (
    <Styled>
      <BreadCrumbsStyled parents={breadCrumbsParents} componentName="MHD" />
      <h2>Volume rendering of Ohmic electric field in MHD turbulence</h2>
      <p>
        The data were generated by a simulation of the incompressible MHD equations on
        a space grid of 1,024<sup>3</sup> points. The magnetic Prandtl number is 1. Animation shows a
        single snapshot from various viewing directions. For more details, see Eyink et al.
        (Nature 2013, <Link href="https://doi.org/10.1038/nature12128" target="_blank">doi:10.1038/nature1212</Link>).
      </p>
      <br />
      <iframe
        src="https://www.youtube.com/embed/5Kmw9n3dat8?si=kSrQiQR5DhaY4fHF"
        title="YouTube video player"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        referrerPolicy="strict-origin-when-cross-origin"
        allowFullScreen
      />
    </Styled>
  );
};